// frontend/react/src/App.tsx
import { useState } from "react";
import SignupForm from "./SignupForm";

function App() {
	const [form, setForm] = useState(new SignupForm());

	function reload (fn: any) {
		if (fn) fn();
		setForm(clone(form));
	}

	function clone(obj: any) {
		var copy = new obj.constructor;
		for (var attr in obj) {
			if (obj.hasOwnProperty(attr)) copy[attr] = obj[attr];
		}
		return copy;
	}

	// async function confirm () {
	// 	const input = {
	// 		name,
	// 		email,
	// 		document,
	// 		password
	// 	}
	// 	const response = await fetch("http://localhost:3000/signup", {
	// 		method: "post",
	// 		headers: {
	// 			"content-type": "application/json"
	// 		},
	// 		body: JSON.stringify(input)
	// 	});
	// 	const output = await response.json();
	// 	setMessage("success");
	// }

	// function fill () {
	// 	setName("John Doe");
	// 	setEmail("john.doe@gmail.com");
	// 	setDocument("97456321558");
	// 	setPassword("asdQWE123");
	// }

	return (
		<div>
			<div>{ form.step }</div>
			<div>{ form.getProgress() }</div>
			{ form.step === 1 && <div>
				<div>
					<input className="input-name" value={form.name} onChange={(e) => reload(() => form.name = e.target.value)}/>
				</div>
				<div>
					<input className="input-email" value={form.email} onChange={(e) => reload(() => form.email = e.target.value)}/>
				</div>
				<div>
					<input className="input-document" value={form.document} onChange={(e) => reload(() => form.document = e.target.value)}/>
				</div>
			</div>}
			{ form.step === 2 && <div>
				<div>
					<input className="input-password" value={form.password} onChange={(e) => reload(() => form.password = e.target.value)}/>
				</div>
				<div>
					<input className="input-confirm-password" value={form.confirmPassword} onChange={(e) => reload(() => form.confirmPassword = e.target.value)}/>
				</div>
			</div>}
			<span className="span-error">{ form.error }</span>
			<button className="button-fill" onClick={() => reload(() => form.fill())}>Fill</button>
			{ form.step === 2 && <button className="button-previous" onClick={() => reload(() => form.previous())}>Previous</button>}
			{ form.step === 1 && <button className="button-next" onClick={() => reload(() => form.next())}>Next</button>}
			{ form.step === 2 && <button className="button-confirm" onClick={() => reload(() => form.confirm())}>Confirm</button>}
		</div>
	)
}

export default App

// frontend/vue/src/App.vue
<script setup lang="ts">
    import { ref, inject } from "vue";
    import AccountGateway, { AccountGatewayHttp } from "./infra/gateway/AccountGateway";
    import SignupForm from "./domain/SignupForm";

    let form = ref(new SignupForm());

    const accountGateway = inject("accountGateway") as AccountGateway;

    form.value.register("confirmed", async (event) => {
        const output = await accountGateway.signup(event);
        form.value.accountId = output.accountId;
    });

</script>

<template>
    <div>
        <div>
            <span class="span-step" @click="form.fill()">{{ form.step }}</span>
        </div>
        <div>
            <span class="span-progress">{{ form.getProgress() }}%</span>
        </div>
        <div>
            <span class="span-error">{{ form.error }}</span>
        </div>
        <div>
            <span class="span-account-id">{{ form.accountId }}</span>
        </div>
        <div v-if="form.step === 1">
            <div>
                <input class="input-name" type="text" v-model="form.name" placeholder="Name"/>
            </div>
            <div>
                <input class="input-email" type="text" v-model="form.email" placeholder="Email"/>
            </div>
            <div>
                <input class="input-document" type="text" v-model="form.document" placeholder="Document"/>
            </div>
        </div>
        <div v-if="form.step === 2">
            <div>
                <input class="input-password" type="text" v-model="form.password" placeholder="Password"/>
            </div>
            <div>
                <input class="input-confirm-password" type="text" v-model="form.confirmPassword" placeholder="Confirm Password"/>
            </div>
        </div>
        <button v-if="form.step > 1" class="button-previous" @click="form.previous()">Previous</button>
        <button v-if="form.step === 1" class="button-next" @click="form.next()">Next</button>
        <button v-if="form.step > 1" class="button-confirm" @click="form.confirm()">Confirm</button>
    </div>
</template>

<style>
</style>
